### ISSUE TITLE
Mauvaise indentation des commentaires Actions complexes.

### ISSUE THREAD

**Issue by xcregut** [LouisBrousse/devin#2]
https://github.com/LouisBrousse/devin/blob/9c4664b9a61a7656461b68b09d0667d80189343c/Devin3.py#L20
Les commentaires correspondant aux actions complexes doivent être alignés avec les instructions qui suivent.
Il faut aussi utiliser des verbes à l'infinitif.

**Comment by LouisBrousse** [comment]
fait
