### ISSUE TITLE
Commentaires mal placés

### ISSUE THREAD

**Issue by xcregut** [LouisBrousse/devin#3]
https://github.com/LouisBrousse/devin/blob/9c4664b9a61a7656461b68b09d0667d80189343c/Devin3.py#L28
Ces trois commentaires sont mal placés (soit devant le if pour décrire tout le if elif else, soit devant les instructions qui sont dans le if) et inutiles car ils correspondent à ce que fait la fonction appelée.

**Comment by LouisBrousse** [comment]
commentaires supprimés
