### ISSUE TITLE
Mal placé

### ISSUE THREAD

**Issue by xcregut** [LouisBrousse/devin#5]
https://github.com/LouisBrousse/devin/blob/9c4664b9a61a7656461b68b09d0667d80189343c/Devin3.py#L36
à faire à la fin du programme, pas dans une boucle.

**Comment by LouisBrousse** [comment]
OK modification faite mais pour refaire fonctionner j'ai du enleve les lignes 14 et 15. (dans def main() le lancement des fonctions des différents jeux de devin).
