### ISSUE TITLE
Mauvais commentaire

### ISSUE THREAD

**Issue by xcregut** [LouisBrousse/devin#9]
https://github.com/LouisBrousse/devin/blob/9c4664b9a61a7656461b68b09d0667d80189343c/Devin3.py#L93
Ici vous ne calculez pas la proposition.

**Comment by LouisBrousse** [comment]
Modifié par "Initier le calcul de la proposition"

**Comment by LouisBrousse** [comment]
Modifié par "Initier le calcul de la proposition"
